---
title: "Xerrada Beranui"
---

## XERRADA BERANUI

# 1. PROCESOS

    PREPARACIÓN: Debemos limpiar y esterilizar las partes del equipo que
    vayamos a utilizar.

    MACERACIÓN: Es el proceso en el cual el almidón de los granos de malta
    se convierten en azúcares fermentables. Sumergimos los granos de malta en
    agua caliente y se produce un líquido dulce que llamamos "mosto".

    LAVADO: Rociamos con agua la superficie del grano para extraer los azú-
    cares fermentables.

    EBULLICIÓN: Herviremos el mosto durante una hora, de esa manera es-
    terilizaremos el mosto y añadiremos los lúpulos para que nos proporcionen
    amargor, sabor y aroma.

    ENFRIAMIENTO: Enfriamos el mosto hasta la temperatura de de fermen-
    tación para poder añadir la levadura sin que se mueran las células.

    FERMENTACIÓN: Se introduce el mosto en un fermentador durante apro-
    ximadamente una semana, los azúcares del mosto se convertirán en alcohol.

    CEBADO Y TRASIEGO: Cuando ha fermentado añadimos el azúcar de ce-
    bado para condicionar la cerveza y añadir carbonatación. Deberemos trasegar
    la cerveza a un recipiente donde la almacenemos.

    ACONDICIONAMIENTO: Dependiendo del estilo y de la receta debere-
    mos dejarla cerveza un tiempo para que se clarifique y permita madurar los
    sabores.

    SERVIDO: La cerveza ya la tendremos lista para beber.

# 2. INGREDIENTES

## MALTA

La malta es un cereal que comienza a germinar y se detiene el proceso. Mediante el malteado se producen enzimas que permitirán al almidón del cereal se convierta en azúcares fermentables.
Principalmente cebada (avena) pero también trigo y centeno.
El proceso básicamente es el siguiente:
Se sumerge el cereal en agua con lo que comienza a germinar, cuando las
raicillas han crecido se detiene el proceso secándolo con aire caliente y se
extraen las raicillas. Se tuesta, maltas muy poco tostadas tienen
elevado po- der enzimático o diastático por lo que producirán grandes
cantidades de azú- car al macerar, mientras que las maltas muy tostadas
tendrán poco poder enzimático o diastático produciendo pocos azúcares
por lo que se utilizarán principalmente para dar color, sabor y aroma a
la cerveza.

## MALTAS BASE

-   Maltas base pálidas
-   Maltas base tostadas más oscuras
-   Maltas de trigo
-   Maltas de centeno

MALTAS ESPECIALES

-   Maltas caramelo
-   Maltas ámbar (Amber)
-   Maltas tostadas

EL COLOR.

Hay tres escalas aceptadas mundialmente:

-   La European Brewing Convention (EBC)
-   La Standard Reference Method (SRM)
-   Los grados Lovibond (oL)

Los grados Lovibond son prácticamente iguales a los SRM, y éstos son el
doble de los EBC. Van del 0 hasta 138 / 70, desde una Lager Pálida a una
Imperial Stout.

ADJUNTOS. Trigo torrefactado Espelta Arroz en copos Cebada tostada Avena
en copos Maíz en copos Azúcar cande Miel Melaza

LÚPULOS.

El lúpulo es una planta trepadora cuyas flores femeninas con forma de
piña se secan. El lúpulo que añadiremos al inicio de la ebullición nos
servirá para producir amargor equilibrando el alcohol y añadiendo
suavidad. Los lúpulos que añadimos en el final de la ebullición son los
que proporcionarán aroma y sabor.

Ácidos Alfa: Con propiedades antibacterianas aportarán amargor, se mide
como un porcentaje y a más valor le corresponde más nivel de amargor. No
son solubles al agua por lo que se deben de hervir y cuanto más tiempo
lo hagan más ácidos alfa liberarán y, por tanto, más amargor. Ácidos
Beta: Aportan aroma y no requieren ebullición.

## CONSERVACIÓN DEL LÚPULO.

El lúpulo seco con el aire y con la luz se deteriora rápidamente, para
evitar- lo se deberán sellar herméticamente y congelar. Se utilizarán
sin descongelar.

LEVADURA. Existen más de 1500 tipos de levaduras aunque sólo utiliza-
mos una para elaborar cerveza, laSaccharomyces cerevisiae. La levadura
se alimenta de los azúcares y de los hidratos de carbono que están
presentes en el mosto y producen dióxido de carbono y etanol (alcohol)
además de varios subproductos como principalmente ésteres, aceites de
Fu- sel y diacetilo.

-   Ésteres, aportan características importantes de sabor,
    principalmente sabores afrutados complejos. La cantidad dependerá de
    la temperatura de fermentación, a más temperatura, más ésteres.
-   Aceites de Fusel son una mezcla de varios compuestos químicos. Dan
    notas picantes y especiadas. Depende de lo que se noten podrán ser
    un defecto.
-   Diacetilo, también depende de lo que se aprecie podrá ser un
    defecto. Puede dar sabores de mantequilla y de caramelo. El sabor de
    diacetilo lo "limpian"las levaduras por lo que puede indicar una
    pobre fermenta- ción.

LEVADURAS DE FERMENTACIÓN ALTA Y BAJA.

-   Levaduras de fermentación alta: Temperaturas elevadas (16 y 24oC).
    Se utlizan para producir Ales. Producen muchos ésteres complejos por
    lo que las cervezas son tienen más aromas y sabores.
-   Levaduras de fermentación baja: Temperaturas más bajas (7 y 15oC).
    Se utilizan para producir Lagers. Son cervezas con un sabor más lim-
    pio y neutro. Tienen menos ésteres y más diacetilo. Para eliminar el
    diacetilo los últimos días se aumenta la temperatura de
    fermentación.

FLOCULACIÓN.

La floculación mide la facilidad de precipitación de la levadura en suspensión, lo cual afectará al aclarado de la cerveza, a mayor velocidad de floculación, más aclarado.

## ATENUACIÓN.

Es una medición que nos dará el valor de la eficiencia de la levadura en fermentar los azúcares disponibles. Se da como un porcentaje. Las que tienen valores altos de atenuación tienen bajas velocidades de floculación y al revés.
    REUTILIZACIÓN DE LEVADURAS.

## AGUA.

-   Aguas blandas, aguas con bajo contenido mineral, normalmente aguas
    que discurren por rocas. Nos servirán para elaborar cervezas pálidas
    (pH bajo)
-   Aguas duras, aguas con un alto contenido mineral. Cervezas con más
    bicarbonatos y calcios, pH altos, para cervezas más densas tipo
    Stout.

```{=html}
<!-- -->
```
    El nivel de PH mide la acidez o la alcalinidad. El pH debe ser superior a 5,
    para que las maltas "funcionen"bien.

## HIERBAS, FLORES, FRUTOS Y ESPECIAS.

Semillas de cardamono Semillas de coriandro Anís estrellado Canela en
rama Raiz de regaliz Vainas de vainilla Chile Bayas de enebro Rosa
mosqueta Bayas de saúco Flores de saúco Hojas de lima kaffir Fresas
Frambuesas Cerezas Piel de naranja Piel de limón y de lima Ápices de
brezo MÉTODOS DE ELABORACIÓN Kit Extracto de malta Elaboración todo
grano Elaboración todo grano con tres niveles. Método todo grano en
bolsa (BIAB), no es tan eficiente en la extracción de los azúcares
fermentables del cereal.

    HIGIENE

# 3. TIPOS DE ELABORACIÓN

KIT: La mejor manera de comenzar. La que menos material, conocimientos y dinero requiere. Por contra es la que menos podemos personalizar.

EXTRACTO DE MALTA: Intermedio. Se puede combinar extracto de malta con algo de malta. Se añaden los lúpulos igual que en una todo grano.

TODO GRANO:

-   Maceración: La temperatura ideal está entre los 65 y 68oC. El extre-
    mo superior produce menos azúcares fermentables, ideal para cervezas
    suaves y dulces, mientras que el extremo inferior produce más
    azúcares por lo que nos irá bien en cervezas secas y fuertes.
-   Tipos de maceración: ◦ Por infusión simple: Se mantiene constante la
    temperatura. ◦ Por infusión escalonada: Se comienza a una baja
    temperatura, se aumenta y se mantiene un tiempo, y finalmente, se
    vuelve a au- mentar y mantener. Aumenta el rendimiento de la malta.
    ◦ Por maceración por decocción: Se mezcla a 35-40oC y se aumenta la
    temperatura de forma escalonada. Se retira una parte y se hierve una
    porción del macerado que luego se devuelve al principal. Se puede
    hacer una, dos o tres veces, macerado por decocción simple, doble o
    triple.
-   Lavado:Enjuagaremos los azúcares fermentables del macerado y pasa-
    remos el mosto al hervidor. El agua del lavado debe estar entre 74 y
    77 oC. ◦ Lavado continuo. Rociamos el agua mientras extraemos la
    misma cantidad que depositamos en el hervidor. ◦ Lavado por etapas.
    Añadimos agua caliente a la maceración, re- movemos y dejamos 20
    minutos en infusión, se drena y devuelve a la infusión. ◦ No lavado.
    Se pierde gran cantidad de azúcares.
-   Ebullición. Nos servirá para poder esterilizar el mosto además de
    aña- dir el lúpulo lo cual añadirá, por los alfa-acidos sabor y
    aroma.
-   Adicción de la levadura: ◦ Levadura seca: No se pasa con el tiempo
    si no está caducada. Hi- dratación de la levadura seca. ◦ Levadura
    líquida: No es aconsejable guardarla más de cuatro me- ses. Se ha de
    dejar dos días fermentando.

DRY HOPPING: Consiste en añadir lúpulo al fermentador pasados unos 4 días, en una bolsa. El sabor será más intenso pues no han marchado aromas con la primera fermentación ni con el calor de la ebullición. El alcohol matará las bacterias que pueda tener el lúpulo. A la semana se retira para evitar aromas no deseados.
   
CLARIFICANTES: Sirven para clarificar la cerveza al aglomerar y enviar al fondo las partículas en suspensión.
    ◦ Protofloc
    ◦ Issinglass(cola de pescado)
    ◦ Irish Moss(Musgo de Irlanda)
    ◦ Cold Crash

-   Fermentación: Se divide en tres fases:

    ◦ Primera fase, lag o adaptativa. Las células de levadura se multiplican. Se forma elkrausen. No debería superar las 24 horas.
    ◦ Segunda fase, primaria o atenuativa. La levadura fermenta los azúcares del mosto y produce alcohol, dióxido de carbono y otro compuestos.
    ◦ Fase secundaria o de acondicionamiento. La levadura elimina sub-
    productos no deseados, ésteres y diacetilo, obteniendo una cerveza
    pálida y de sabor limpio.
    OXÍGENO Y TEMPERATURA.
    En la fase lages la única parte de la elaboración en la que es necesaria
    la presencia de oxígeno para que las células de levadura puedan multi-
    plicarse.
    Cada cepa de levadura deberá mantenerse entre las temperaturas ade-
    cuadas, las de temperaturas más bajas normalmente tienen sabores más
    limpios que las que fermentan a temperaturas más elevadas.
    CÁLCULO DEL APV.
    Diferencia entre DF y DO multiplicado por 105 y tenemos el porcenta-
    je de alcohol en peso, si volvemos a multiplicar por 1,25 tendremos el
    porcentaje de alcohol por volumen. (APV)

-   Cebado y trasiego. Las cervezas deberemos cebarlas con azúcar antes
    de embotellar o embarrilar. La cantidad de azúcar (de maiz o de
    caña), dextrosa, extracto de malta, dependerá del tipo de cerveza y
    buscare- mos un volumen de CO2 (Volumen de CO2 por volumen de
    cerveza). Van desde 1,5 a 3,75 las más carbonatadas. Durante el
    trasiego evitaremos salpicar para no introducir oxígeno. Las chapas
    son de 29 mm. y de 26 mm.

-   Servido desde una botella. Temperatura entre 9 y 12oC, las Lagers
    más frías. Comenzamos a unos 45oy suavemente, levantamos el vaso
    para que se forme espuma y evitamos que caigan sedimentos.

-   Etiquetado. Páginas web. Pegar con leche. Impresora láser.
