

---
author:
- |
  **Rafael Llanas Villanueva**\
title: " **Relats Curts presentats al Concurs de la Vall Fosca** "
editor_options: 
  markdown: 
    wrap: 72
---
# Joanot de Gramanet, matemàtic.

Sí, ja conec la història dels ponts de Königsberg, lo del tal Euler i que tot
plegat diuen que així va començar el que més tard es va conèixer com “la
teoria dels grafs”, però deixeu-me que us expliqui una història que no pel fet
de ser inventada, deixa de ser veritat.

«Era a començaments del segle XVII, tot i que a en “Joanot de Gramanet”això no fos un fet que l’importés gaire. Un bon dia“pastorant” pels
prats de Serraspina, va pensar quelcom que el mantindria ocupat durant uns
quants dies, i ara, amb el permís que em concedeix el temps transcorregut,
em permeto explicar-vos quin seria, més o menys, el seu dubte:

-És possible unir visualment els dinou pobles de la Vall Fosca sense passar
dues vegades pel mateix lloc?

En Joanot rumiava i rumiava, començava per Cabdella i acabava a Estavill, i tornava a rumiar, començava per Envall i acabava a Aiguabella, i
torna que torna, pensa que pensa... »

El cas és que en Joanot no va explicar mai a ningú la seva idea, i per això
només la coneixia jo. Ara voldria compartir-la amb tots vosaltres per a que
m’ajudessiu a esbrinar si la seva conjectura tenia solució o no, i potser també
per a que reconeguem d’una vegada per totes, que el veritable descobridor
de “la teoria dels grafs”va ser en “Joanot de Gramanet”i també, per què no
dir-ho, que jo vaig ser l’inventor de la paraula “postveritat”,al cap i a la fi,
dos veïns de la Vall Fosca.


# Canvis
La primera crida a l’oració va sortir de la mesquita d’Estavill i aviat se li
van unir les d’Aguirò, Antist, Oveix i Castell-estaò i durant una estona la Vall
Fosca es va quedar immersa en una monòtona cantarella.

Moltes coses havien canviat des que el nivell de les aigües havia començat a
pujar inundant progressivament Pobleta, la Plana, Molinos... el capitalisme hi
havia fracassat i el canvi climàtic va ser molt pitjor del que els experts havien
imaginat, als camps els trossos s’havien convertit en deserts i les estacions cada
vegada se semblaven més a l’estiu, un estiu que ara durava tot un any.

De mica en mica les maneres de vestir es van anant adaptant a les altes
temperatures, el te va substituir a l’alcohol i la gent va buscar nous deus que
satisfessin les seues pors, els seus temors i els seus dubtes i així, adaptant els
seus costums, la nova religió és va començar a introduir a totes les llars de la Vall.

Aviat seria la festa del corder i les famílies a les seves cases ja s’anaven preparant, només els més recalcitrants continuaven amb l’antic costum de menjar
abans uns quants calçots.

Les aigües havien baixat del Nord però la cultura, un altre cop, ens va arribar
des del Sud...


# Ell, ell que no era ningú. 

Puta merda!. Sí, Puta merda!, aquestes van ser les últimes paraules que va
pronunciar.

Paraules plenes de ràbia, de fàstic, de desesperació, paraules que, per sobre
de tot, demostraven incomprensió. Incomprensió per com havia arribat fins
allà... ell, que mai va sàpiguer de bàndols, ni de polítiques, ni d’hòsties... ell,
que sempre va fugir capcot de qualsevol tumult, de qualsevol baralla, de
qualsevol discussió... ell, que per no tindre no tenia ni nom, unes vegades ere
“lo pastoret” i d’altres “lo fato de ca l’Antònia”...

Clar que havia sentit que hi havia una guerra, que hi havia dos bàndols i que
es mataven entre ells, però això no anava amb ell, o almenys això pensava i, a
més aquesta guerra no era la seva, la seva era la de lluitar per protegir el seu
ramat, contra el llop, contra les tronades o contra la set. L’altre l’importava,
però poc.

Però ningú no pot escapolir-se d’una barbàrie que arriba com una crescuda
que arrasa tot el que troba, tu no pots ignorar allò que no vol ignorar-te, i
la guerra tampoc va passar de llarg a la Vall Fosca, també hi va arribar
la crescuda que aquesta vegada anava a contracorrent puiant per tot lo
Flamisell, recorrent els pobles, cobrint-los d’una pàtina de vergonya i sang.

Ningú no sabia exactament el per què. Uns deien que si uns trossos, que si
una dona, que si l’amo del ramat, però la bogeria de la guerra també el va
enxampar... a ell, a qui menys s’ho esperava, a qui menys l’importava.

Puta merda! Sí, Puta merda! És trist acomiadar-se del món amb aquestes
paraules.

“Fuego” va ser l’última que va sentir abans de caure a terra...




